import Link from "next/link";
import { ArrowLeft, ArrowUpLeft, Lightbulb, MapPin, MoveUpLeft, Sparkles, Zap, Phone, MessageCircle } from "lucide-react";
import { ClosingCta } from "@/components/shell";
import { collections } from "@/lib/collections";
import { site } from "@/lib/site";
import { pageGraph } from "@/lib/seo";
import { StructuredData } from "@/components/structured-data";

const iconMap = { indoor: Lightbulb, outdoor: Sparkles, electric: Zap };

export default function Home() {
  return <main id="main">
    <section className="hero"><div className="container hero-grid">
      <div className="hero-content"><span className="hero-kicker"><span className="line-dot" /> نخدم مدينة الرياض · {site.hoursLabel}</span><h1>عبدالحكيم للكهرباء <em>والإنارة الحديثة.</em></h1><p>خدمات تأسيس الكهرباء والإنارة الداخلية والخارجية داخل مدينة الرياض. وضّح احتياجك واتصل بعبدالحكيم أو أرسل التفاصيل عبر واتساب لتنسيق الخدمة.</p><div className="hero-actions"><Link href="/#collections" className="button button-glow">تصفّح المجالات <ArrowLeft size={19} /></Link><a href={site.telephoneUrl} className="button button-outline">اتصل الآن <Phone size={18} /></a><a href={site.whatsappUrl} target="_blank" rel="noopener noreferrer" className="button button-outline">واتساب <MessageCircle size={18} /></a></div><div className="hero-meta"><span><Lightbulb size={16} /> إنارة داخلية وخارجية</span><span><Zap size={16} /> مستلزمات كهرباء</span></div></div>
      <div className="light-scene" role="img" aria-label="رسم تجريدي لثلاثة مصابيح معلقة بأضواء دافئة"><span className="scene-grid" /><span className="scene-label">تفاصيل الإضاءة</span><span className="wire wire-one" /><span className="wire wire-two" /><span className="wire wire-three" /><span className="lamp lamp-one"><i /></span><span className="lamp lamp-two"><i /></span><span className="lamp lamp-three"><i /></span><span className="scene-note">ضوءٌ يغيّر<br />إحساس المكان.</span><span className="scene-arc" /></div>
    </div><div className="container hero-bottom"><div className="hero-bottom-address"><span className="hero-bottom-icon"><MapPin size={20} /></span><span><small>نطاق الخدمة</small><strong>{site.serviceArea} · {site.hoursLabel}</strong></span></div><a href={site.telephoneUrl}><bdi dir="ltr">{site.phoneDisplay}</bdi> <Phone size={17} /></a></div></section>

    <section className="section intro-section"><div className="container intro-grid"><div><span className="eyebrow">ابدأ من احتياجك</span><h2>اختيار الإنارة يبدأ <span>من تفاصيل المكان.</span></h2></div><div><p>نوع المساحة، طريقة استخدامها، والمواصفة المطلوبة هي أسئلة تساعدك قبل اختيار قطعة إنارة أو مستلزم كهربائي. رتّبنا المجالات في صفحات واضحة لتبدأ منها.</p><Link href="/about" className="text-link">تعرّف على النشاط <MoveUpLeft size={18} /></Link></div></div></section>

    <section className="section collections-section" id="collections"><div className="container"><div className="section-header"><div><span className="eyebrow">المجالات</span><h2>من الفكرة <span>إلى السؤال المناسب.</span></h2></div><p>استعرض كل مجال، ثم اسأل النشاط عن الأصناف والمواصفات المتاحة قبل التواصل.</p></div><div className="collection-grid">{collections.map((item, i) => { const Icon = iconMap[item.visual]; return <Link className={`collection-card visual-${item.visual}`} href={`/collections/${item.slug}`} key={item.slug}><div className="collection-art" aria-hidden="true"><span className="art-grid" /><span className="art-halo" /><Icon size={94} strokeWidth={1.1} /><span className="art-index">0{i + 1}</span></div><div className="collection-copy"><span className="eyebrow">{item.eyebrow}</span><h3>{item.shortTitle}</h3><p>{item.description}</p><span className="collection-more">استكشف المجال <ArrowUpLeft size={19} /></span></div></Link>; })}</div></div></section>

    <section className="section method-section"><div className="container method-grid"><div className="method-visual" aria-hidden="true"><span className="orbit orbit-one" /><span className="orbit orbit-two" /><span className="orbit orbit-three" /><span className="core-light"><Lightbulb size={82} strokeWidth={1.1} /></span><span className="tiny-star star-one">✦</span><span className="tiny-star star-two">✦</span><span className="visual-label">فكرة واضحة · اختيار أدق</span></div><div className="method-copy"><span className="eyebrow">قبل التواصل</span><h2>ثلاث معلومات <span>تسهّل السؤال.</span></h2><p>عند السؤال عن إنارة أو مستلزم كهربائي، ابدأ بما تعرفه بالفعل. التفاصيل البسيطة تساعد في تحديد الصنف المناسب.</p><div className="method-list"><div><strong>01</strong><span><b>المكان</b><small>داخلي أم خارجي؟ وما أبعاد المساحة؟</small></span></div><div><strong>02</strong><span><b>الاحتياج</b><small>إضاءة عامة، تفصيل جمالي، أو مستلزم بمواصفة محددة؟</small></span></div><div><strong>03</strong><span><b>المواصفة</b><small>جهز المقاسات أو صورة الصنف أو رقم الموديل إن وجد.</small></span></div></div></div></div></section>

    <section className="section location-section"><div className="container location-grid"><div><span className="eyebrow">نطاق الخدمة</span><h2>نخدمك داخل <span>مدينة الرياض.</span></h2><p>أرسل موقع الخدمة ونوع الاحتياج لتنسيق التفاصيل. {site.hoursDescription}</p><a className="button button-dark" href={site.whatsappUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={19} /> نسّق الخدمة عبر واتساب <ArrowUpLeft size={18} /></a></div><div className="location-card"><div className="map-pattern" aria-hidden="true"><span className="road road-a" /><span className="road road-b" /><span className="road road-c" /><span className="road road-d" /><span className="pin-glow"><MapPin size={31} fill="currentColor" /></span><span className="map-disclaimer">رسم توضيحي لنطاق الخدمة</span></div><div className="location-card-caption"><span>نطاق الخدمة</span><strong>مدينة الرياض</strong><small>الكهرباء والإنارة الحديثة · {site.hoursLabel}</small></div></div></div></section>

    <section className="section faq-teaser"><div className="container faq-banner"><div><span className="eyebrow">قبل الطلب</span><h2>كل سؤال له بداية واضحة.</h2><p>نطاق الخدمة، رقم التواصل، وما الذي تجهزه قبل الاستفسار؛ ستجد الإجابات العملية في صفحة واحدة.</p></div><Link href="/faq" className="button button-outline-dark">الأسئلة الشائعة <ArrowLeft size={18} /></Link></div></section>
    <ClosingCta /><StructuredData data={pageGraph("/", site.name, site.description)} />
  </main>;
}

